asdifklhjalk

diff --git a/.github/workflows/degradation_check copy.yml b/.github/workflows/degradation_check copy.yml
--- a/.github/workflows/degradation_check copy.yml
+++ b/.github/workflows/degradation_check copy.yml
@@ -1,67 +1,97 @@
 name: Benchmarks and build time
 
 on:
+  push:
+    branches:
+      - "**"
   pull_request:
     branches: [main]
     types: [opened, reopened, synchronize]
+  release:
+    types: [published]
 
 jobs:
-  runBenchmarks:
+  Criterion_benchmarks:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+      - name: Run json_like_bench
+        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
+        uses: boa-dev/criterion-compare-action@v3.2.4
+        with:
+          cwd: /workspaces/tailcall/benches/criterion
+          benchName: json_like_bench
+          defaultFeatures: false
+          branchName: ${{ github.base_ref }}
+          token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Install criterion-compare-action
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Run json_like_bench
+        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
+        uses: boa-dev/criterion-compare-action@v3.2.4
+        with:
+          benchName: json_like_bench
+          defaultFeatures: false
+          branchName: ${{ github.base_ref }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Run impl_path_string_for_evaluation_context
+        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
+        uses: boa-dev/criterion-compare-action@v3.2.4
+        with:
+          benchName: impl_path_string_for_evaluation_context
+          defaultFeatures: false
+          branchName: ${{ github.base_ref }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Run data_loader_bench
+        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
+        uses: boa-dev/criterion-compare-action@v3.2.4
+        with:
+          benchName: data_loader_bench
+          defaultFeatures: false
+          branchName: ${{ github.base_ref }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Run request_template_bench
+        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
+        uses: boa-dev/criterion-compare-action@v3.2.4
+        with:
+          benchName: request_template_bench
+          defaultFeatures: false
+          branchName: ${{ github.base_ref }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      # Add a step to analyze benchmark percentage differences
+      - name: Check Benchmark Changes
+        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published') }}
         run: |
-          mkdir -p ~/.cargo/bin
-          curl -LsSf https://github.com/boa-dev/criterion-compare-action/releases/download/v3.2.4/critcmp -o ~/.cargo/bin/critcmp
-          chmod +x ~/.cargo/bin/critcmp
+          # Run the critcmp command and capture its output
+          output=$(/home/runner/.cargo/bin/critcmp base changes)
 
-      - name: Run benchmarks and comment on PR
-        if: github.event_name == 'pull_request'
-        run: |
-          # Run benchmarks
-          critcmp base changes
-
-          # Comment on the pull request
-          output=$(critcmp base changes)
+          # Print the captured output
           echo "$output"
+
+          # Use awk to calculate percentage differences and fail the CI if the difference is more than 10%
           awk 'NR > 2 {
               group=$1
               base=$7
               changes=$3
 
-              gsub(/[^\-0-9\.]/, "", changes)
-              gsub(/[^\-0-9\.]/, "", base)
+              gsub(/[^\-0-9\.]/, "", changes)  # Extract only numerical values
+              gsub(/[^\-0-9\.]/, "", base)     # Extract only numerical values
 
+              # Ensure changes and base values are not empty
               if (changes != "" && base != "") {
-                  diff = changes - base
-                  percentage = (diff / base) * 100
+                  diff = changes - base  # Calculate the absolute difference
+                  percentage = (diff / base) * 100  # Calculate the percentage difference
 
                   if (percentage > 10) {
                       printf "Percentage change for %s exceeds 10%%: %.2f%%\n", group, percentage
-                      exit 1
+                      exit 1  # Exit script to indicate CI failure
                   }
               }
-          }' <<< "$output" | \
-          if [[ $? -eq 0 ]]; then
-              COMMENT="Benchmarks Passed! :white_check_mark:"
-          else
-              COMMENT="Benchmarks Failed! :x:"
-          fi
-          echo "$COMMENT"
-          echo "::set-output name=COMMENT::$COMMENT"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Comment on PR
-        if: github.event_name == 'pull_request'
-        run: |
-          COMMENT="${{ needs.runBenchmarks.outputs.COMMENT }}"
-          echo "Comment: $COMMENT"
-          echo "$COMMENT" | gh pr comment ${{ github.event.number }} --body -
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#asf
+          }' <<< "$output"
