Update micro_benchmarks.yml

diff --git a/.github/workflows/micro_benchmarks.yml b/.github/workflows/micro_benchmarks.yml
--- a/.github/workflows/micro_benchmarks.yml
+++ b/.github/workflows/micro_benchmarks.yml
@@ -7,7 +7,8 @@ on:
       - main
   push:
     branches:
-      - "**"      
+      - "**"
+
 jobs:
   Micro-benchmarks:
     name: Criterion Benchmarks
@@ -18,7 +19,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Install Critcmp
-        run: cargo install critcmp
+        run: cargo install critcmp || echo "Critcmp is already installed"
 
       - name: Benchmark changes
         run: |
@@ -26,6 +27,7 @@ jobs:
           cargo bench --bench data_loader_bench -- --save-baseline new_branch
           cargo bench --bench request_template_bench -- --save-baseline new_branch
           cargo bench --bench json_like_bench -- --save-baseline new_branch
+
       - name: Fetch base branch
         run: git fetch
 
@@ -38,36 +40,35 @@ jobs:
           cargo bench --bench data_loader_bench -- --save-baseline main_branch
           cargo bench --bench request_template_bench -- --save-baseline main_branch
           cargo bench --bench json_like_bench -- --save-baseline main_branch
+
       - name: Run shell script
         run: |
           critcmp main_branch new_branch | awk 'NR>2 {
-           item = $1
-           before = $7
-           after = $3
-           before_val = ($7 ~ /ns/) ? $7 : ($7 ~ /µs/) ? $7 * 1000 : ($7 ~ /ms/) ? $7 * 1000000 : "invalid"
-           after_val = ($3 ~ /ns/) ? $3 : ($3 ~ /µs/) ? $3 * 1000 : ($3 ~ /ms/) ? $3 * 1000000 : "invalid"
-           temp1 = before_val
-           temp2 = after_val
-           if (before_val != "invalid" && after_val != "invalid") {
-               change = ((after_val - before_val) / before_val) * 100
-               gsub("%", "", change)  # Remove '%' symbol
-               printf "| %-30s | %-20s | %-20s | %-10.2f |\n", item, before, after, change >> "output_file.txt"
-               if (change > 10) {
-                   echo "Percentage change exceeds 10%. Failing the workflow."
-                   exit 1
-               }
-           }
-           else {
-               echo "Invalid units detected for %s. Failing the workflow."
-               exit 1
-           }
+            item = $1
+            before = $7
+            after = $3
+            before_val = ($7 ~ /ns/) ? $7 : ($7 ~ /µs/) ? $7 * 1000 : ($7 ~ /ms/) ? $7 * 1000000 : "invalid"
+            after_val = ($3 ~ /ns/) ? $3 : ($3 ~ /µs/) ? $3 * 1000 : ($3 ~ /ms/) ? $3 * 1000000 : "invalid"
+            temp1 = before_val
+            temp2 = after_val
+            if (before_val != "invalid" && after_val != "invalid") {
+              change = ((after_val - before_val) / before_val) * 100
+              gsub("%", "", change)  # Remove '%' symbol
+              printf "| %-30s | %-20s | %-20s | %-10.2f |\n", item, before, after, change >> "output_file.txt"
+              if (change > 10) {
+                echo "Percentage change exceeds 10%. Failing the workflow."
+                exit 1
+              }
+            }
+            else {
+              echo "Invalid units detected for %s. Failing the workflow."
+              exit 1
+            }
           }'
-      - name: Debug Info
-        run: |
-          echo "Owner: ${{ github.repository_owner }}"
-          echo "Repo: ${{ github.repository }}"
-          echo "Issue Number: ${{ github.event.number }}"
-  
+
+      - name: Create empty output file
+        run: touch output_file.txt
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
@@ -82,9 +83,9 @@ jobs:
           script: |
             const fs = require('fs');
             const fileContent = fs.readFileSync('output_file.txt', 'utf8');
-            const context = github.context;
-            const issue_number = context.payload.issue?.number || context.payload.pull_request?.number;
-  
+            const scriptContext = github.context;
+            const issue_number = scriptContext.payload.issue?.number || scriptContext.payload.pull_request?.number;
+
             console.log(`Issue Number: ${issue_number}`); // Add this line for logging
 
             const comment = `
@@ -95,19 +96,16 @@ jobs:
             ${fileContent}
             </details>
             `;
-  
+
             github.rest.issues.createComment({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
+              owner: scriptContext.repo.owner,
+              repo: scriptContext.repo.repo,
               issue_number: issue_number,
               body: comment
             });
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          debug: false
-          user-agent: actions/github-script
-          result-encoding: json
-          retries: 0
-          retry-exempt-status-codes: 400,401,403,404,422
+          env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
 
   Build_time_compare:
     if: contains(github.event.pull_request.labels.*.name, 'benchmark') || contains(github.event.head_commit.message, 'benchmark')
