Update micro_benchmarks.yml

diff --git a/.github/workflows/micro_benchmarks.yml b/.github/workflows/micro_benchmarks.yml
--- a/.github/workflows/micro_benchmarks.yml
+++ b/.github/workflows/micro_benchmarks.yml
@@ -7,16 +7,22 @@ on:
 
 jobs:
   Micro-benchmarks:
+    name: Criterion Benchmarks
     if: contains(github.event.pull_request.labels.*.name, 'benchmark') || contains(github.event.head_commit.message, 'benchmark')
-    name: criterion_benchmarks
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Install Critcmp
         run: cargo install critcmp
+
+      - name: Benchmark changes
+        run: |
+          cargo bench --bench impl_path_string_for_evaluation_context -- --save-baseline new_branch
+          cargo bench --bench data_loader_bench -- --save-baseline new_branch
+          cargo bench --bench request_template_bench -- --save-baseline new_branch
+          cargo bench --bench json_like_bench -- --save-baseline new_branch
 
       - name: Fetch base branch
         run: git fetch
@@ -33,8 +39,28 @@ jobs:
 
       - name: Run shell script
         run: |
-          chmod +x .github/scripts/check_degradation.sh
-          .github/scripts/check_degradation.sh
+          critcmp main_branch new_branch | awk 'NR>2 {
+           item = $1
+           before = $7
+           after = $3
+           before_val = ($7 ~ /ns/) ? $7 : ($7 ~ /µs/) ? $7 * 1000 : ($7 ~ /ms/) ? $7 * 1000000 : "invalid"
+           after_val = ($3 ~ /ns/) ? $3 : ($3 ~ /µs/) ? $3 * 1000 : ($3 ~ /ms/) ? $3 * 1000000 : "invalid"
+           temp1 = before_val
+           temp2 = after_val
+           if (before_val != "invalid" && after_val != "invalid") {
+               change = ((after_val - before_val) / before_val) * 100
+               gsub("%", "", change)  # Remove '%' symbol
+               printf "| %-30s | %-20s | %-20s | %-10.2f |\n", item, before, after, change >> "output_file.txt"
+               if (change > 10) {
+                   echo "Percentage change exceeds 10%. Failing the workflow."
+                   exit 1
+               }
+           }
+           else {
+               echo "Invalid units detected for %s. Failing the workflow."
+               exit 1
+           }
+          }'
 
       - name: Debug Info
         run: |
@@ -48,14 +74,16 @@ jobs:
         with:
           script: |
             const fs = require('fs');
-            const fileContent = fs.readFileSync('benches/criterion/benchmarks.txt', 'utf8');
+            const fileContent = fs.readFileSync('output_file.txt', 'utf8');
             const issue_number = context.issue.number;
             const comment = `
             <details>
             <summary>Benchmark Results</summary>
+
             | Test                          | Base         | PR               | % change   |
             |-------------------------------|--------------|------------------|------------|
             ${fileContent}
+
             </details>
             `;
             github.rest.issues.createComment({
@@ -64,6 +92,7 @@ jobs:
               issue_number: issue_number,
               body: comment
             });
+
 
   Build_time_compare:
     if: contains(github.event.pull_request.labels.*.name, 'benchmark') || contains(github.event.head_commit.message, 'benchmark')
